language: cpp
sudo: required
dist: bionic
git:
  depth: 1
env:
  global:
  - BUILD_CONFIG=release
  - DEPLOY_BRANCH=travis-$TRAVIS_OS_NAME
  - DEPLOY_DIR=deploy
  - MSBUILD_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
  - DEPENDENCIES_BASE_URL=https://github.com/kevinlul/edopro-vcpkg-cache/releases/download/20201102
addons:
  apt:
    update: true
    packages:
    - p7zip-full
    - libgl1-mesa-dev
    - libglu-dev
    - libasound2-dev
    - libpulse-dev
    - upx-ucl
  homebrew:
    update: true
    packages:
    - dylibbundler
    - p7zip
    - curl
    - fmt
    - nlohmann-json
matrix:
  include:
  - name: "Windows 10"
    os: windows
    env:
    - VCPKG_ROOT=/c/vcpkg
    - VCPKG_DEFAULT_TRIPLET=x86-windows-static
    - VCPKG_LIBS="lua[cpp] libevent sqlite3 bzip2 libjpeg-turbo libpng zlib curl openssl libgit2 fmt nlohmann-json sdl2-mixer[libflac,mpg123,libvorbis] discord-rpc-payload"
    - VCPKG_CACHE_ZIP_URL=$DEPENDENCIES_BASE_URL/installed_x86-windows-static.zip
    - DXSDK_DIR=/c/d3d9sdk/
  - name: "Bionic GCC7"
    os: linux
    compiler: gcc
    env:
    - VCPKG_ROOT="$PWD/vcpkg"
    - VCPKG_LIBS="freetype libevent sqlite3 irrlicht-rectclip curl openssl libgit2 fmt nlohmann-json sdl2-mixer[libflac,mpg123,libvorbis] discord-rpc-payload"
    - VCPKG_CACHE_7Z_URL=$DEPENDENCIES_BASE_URL/installed_x64-linux.7z
  - name: "Mojave"
    os: osx
    osx_image: xcode11.3
    env:
    - MACOSX_DEPLOYMENT_TARGET=10.11
    - SDKROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk"
    - VCPKG_ROOT=./vcpkg
    - VCPKG_LIBS="freetype libevent openssl libgit2 sdl2-mixer[core,libflac,mpg123,libvorbis] discord-rpc-payload"
    - VCPKG_CACHE_7Z_URL=$DEPENDENCIES_BASE_URL/installed_x64-osx.7z
before_install: ./travis/install-premake5.sh
install: ./travis/dependencies.sh
script: ./travis/build.sh
before_deploy: ./travis/predeploy.sh
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./ocgcore/travis/deploy.sh
  on:
    repo: edo9300/edopro
