version: '{build}'

install:
  - git submodule update --init --recursive

  # environment and system dependency
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-windows.zip ; exit 0"
  - 7z x premake-5.0.0-alpha10-windows.zip
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz ; exit 0"
  - tar xf libevent-2.0.22-stable.tar.gz
  - move libevent-2.0.22-stable event
  - xcopy /E event\WIN32-Code event\include
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://www.lua.org/ftp/lua-5.2.4.tar.gz ; exit 0"
  - tar xf lua-5.2.4.tar.gz
  - move lua-5.2.4\src lua
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://www.sqlite.org/2016/sqlite-amalgamation-3150200.zip ; exit 0"
  - 7z x sqlite-amalgamation-3150200.zip
  - move sqlite-amalgamation-3150200 sqlite3
  
  - appveyor DownloadFile https://github.com/tronkko/dirent/raw/master/include/dirent.h
  - move dirent.h gframe\

  # let premake happy
  - xcopy /E premake\* .
  
  # premake
  - premake5 vs2015
  
configuration: Release

build: 
    project: build/ygo.sln
    parallel: true

after_build:
  - ps: move bin\release\ygopro.exe .

test: off

artifacts:
  - path: ygopro.exe
    name: ygopro(server)

cache:
  - premake-5.0.0-alpha10-windows.zip
  - libevent-2.0.22-stable.tar.gz
  - lua-5.2.4.tar.gz
  - sqlite-amalgamation-3150200.zip
