name: Build EDOPro
on: [push, pull_request]
env:
  BUILD_CONFIG: release
  COVERS_URL: ${{ secrets.COVERS_URL }}
  DEPENDENCIES_BASE_URL: https://github.com/kevinlul/edopro-vcpkg-cache/releases/download/20210219
  DEPLOY_DIR: deploy
  DEPLOY_REPO: ${{ secrets.DEPLOY_REPO }}
  DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
  DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
  FIELDS_URL: ${{ secrets.FIELDS_URL }}
  PICS_URL: ${{ secrets.PICS_URL }}
  UPDATE_URL: ${{ secrets.UPDATE_URL }}
jobs:
  Windows:
    runs-on: windows-2016
    if: >-
      !(
        contains(github.event.head_commit.message, '[ci skip]') ||
        contains(github.event.head_commit.message, '[skip ci]') ||
        contains(github.event.head_commit.message, '[actions skip]') ||
        contains(github.event.head_commit.message, '[skip actions]')
      )
    env:
      DEPLOY_BRANCH: travis-windows
      TRAVIS_OS_NAME: windows
      DXSDK_DIR: /c/d3d9sdk/
      VCPKG_ROOT: /c/vcpkg2
    steps:
    - name: Set custom env vars
      shell: bash
      run: |
        echo "VCPKG_CACHE_ZIP_URL=$DEPENDENCIES_BASE_URL/installed_x86-windows-static.zip" >> $GITHUB_ENV
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        submodules: true
    - name: Install premake
      shell: bash
      run: ./travis/install-premake5.sh
    - name: Install dependencies
      shell: bash
      run: ./travis/dependencies.sh
    - name: Build
      shell: bash
      run: ./travis/build.sh
    - name: Predeploy
      shell: bash
      run: ./travis/predeploy.sh
    - name: Deploy
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: ./ocgcore/travis/deploy.sh

  Linux-gcc-7-5-0:
    runs-on: ubuntu-latest
    if: >-
      !(
        contains(github.event.head_commit.message, '[ci skip]') ||
        contains(github.event.head_commit.message, '[skip ci]') ||
        contains(github.event.head_commit.message, '[actions skip]') ||
        contains(github.event.head_commit.message, '[skip actions]')
      )
    env:
      DEPLOY_BRANCH: travis-linux
      TRAVIS_OS_NAME: linux
    steps:
    - name: Set custom env vars
      shell: bash
      run: |
        echo "VCPKG_ROOT=$PWD/vcpkg" >> $GITHUB_ENV
        echo "VCPKG_CACHE_7Z_URL=$DEPENDENCIES_BASE_URL/installed_x64-linux.7z" >> $GITHUB_ENV
    - name: Get apt packages
      shell: bash
      run: |
        sudo apt remove libsqlite3-dev
        sudo apt install libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        submodules: true
    - name: Install premake
      shell: bash
      run: ./travis/install-premake5.sh
    - name: Install dependencies
      shell: bash
      run: ./travis/dependencies.sh
    - name: Build
      shell: bash
      run: ./travis/build.sh
    - name: Predeploy
      shell: bash
      run: ./travis/predeploy.sh
    - name: Deploy
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: ./ocgcore/travis/deploy.sh

  Mac-os:
    runs-on: macos-latest
    if: >-
      !(
        contains(github.event.head_commit.message, '[ci skip]') ||
        contains(github.event.head_commit.message, '[skip ci]') ||
        contains(github.event.head_commit.message, '[actions skip]') ||
        contains(github.event.head_commit.message, '[skip actions]')
      )
    env:
      DEPLOY_BRANCH: travis-osx
      TRAVIS_OS_NAME: osx
      VCPKG_ROOT: ./vcpkg2
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
      MACOSX_DEPLOYMENT_TARGET: 10.11
      SDKROOT: /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
    steps:
    - name: Set custom env vars
      shell: bash
      run: |
        echo "VCPKG_CACHE_7Z_URL=$DEPENDENCIES_BASE_URL/installed_x64-osx.7z" >> $GITHUB_ENV
    # - name: Update brew packages
      # shell: bash
      # run: |
        # brew install dylibbundler
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        submodules: true
    - name: Install premake
      shell: bash
      run: ./travis/install-premake5.sh
    - name: Install dependencies
      shell: bash
      run: ./travis/dependencies.sh
    - name: Build
      shell: bash
      run: ./travis/build.sh
    - name: Predeploy
      shell: bash
      run: ./travis/predeploy.sh
    - name: Deploy
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: ./ocgcore/travis/deploy.sh
